### ISSUE TITLE
the bintray link is forbidden

### ISSUE THREAD

**Issue by gouravd** [simolus3/sqlite-native-libraries#1]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:minifyTejimandiProductionReleaseWithR8'.
> Could not resolve all task dependencies for configuration ':app:tejimandiProductionReleaseRuntimeClasspath'.
   > Could not resolve eu.simonbinder:sqlite3-native-library:3.32.3.    
     Required by:                                                       
         project :app > project :sqlite3_flutter_libs                   
      > Could not resolve eu.simonbinder:sqlite3-native-library:3.32.3. 
         > Could not get resource 'https://dl.bintray.com/sbinder/sqlite3-native-library/eu/simonbinder/sqlite3-native-library/3.32.3/sqlite3-native-library-3.32.3.pom'.
            > Could not GET 'https://dl.bintray.com/sbinder/sqlite3-native-library/eu/simonbinder/sqlite3-native-library/3.32.3/sqlite3-native-library-3.32.3.pom'. Received status code 403 from server: Forbidden

**Comment by simolus3** [comment]
This has been fixed in version `sqlite3_flutter_libs: ^0.4.0+1` and later, please update your pubspec or run `flutter pub upgrade`.
